spring.application.name=FastFuriousAPI
# Coordenadas do banco (url, usuário e senha)
spring.datasource.url=jdbc:mysql://172.16.0.30:3306/hdcea_fastfurious_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=hdcea
spring.datasource.password=2diSenai

spring.jpa.show-sql=True
# Essa linha mágica faz o Spring criar a tabela Produto automaticamente no MySQL! ✨
spring.jpa.hibernate.ddl-auto=update
